# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbz-treeregister
  labels:
    app: tbz-treeregister
spec:
  selector:
    matchLabels:
      app: tbz-treeregister
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  tbz-treeregister
      labels:
        app: tbz-treeregister
    spec:
      containers:
      - name: tbz-treeregister
        image: plugin-image
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 6123 
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6123 
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: tbz-treeregister-config
          - secretRef:
              name: tbz-treeregister-secret
        ports:
        - containerPort: 6123
      restartPolicy: Always

