#ENC[AES256_GCM,data:x0MzokxnkuCN1zUvbYgw/rfcrFG2GiLzNyvzdmwXfdCe8J2+8rYyoSzcKfzhwKYUyjAtchtO/Q8ZHA==,iv:areLdJCPHdR/nxNLIkgw0KnqZKmb+r1ltmj3DWFwt68=,tag:7pNJMfF1xU35Ya4y/BlM/A==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: plugin-secret
type: Opaque
data:
    GE_CLIENT_SECRET: ENC[AES256_GCM,data:j+4drvCLEMQHc4/yOPtLp0va0gYWlqmXO7HsEnWnYjTuormUzgcbCCtCgk0=,iv:VmY+XO8ooIuMT7DnjM7EbgKv+FmgwgeD7MDDNyRGKM4=,tag:KlG5Up/7yKKiE6Ry15nyGA==,type:str]
    GE_DB_URL: ENC[AES256_GCM,data:Y/YQNZEkjKCmCOHcxV+cjj9FOstORu06AeeClvgaieQACLgBG5NynHLtA/QdTYjssOR0Bv8hLzapLkai/WmypixNSFyLL8upLIZIXCEbWydS4100efOPvMrtzlyYYmhJxmE2xoCP70uJLbneW34GF1YmW8wjytoUk+p4yQ==,iv:4clyJ+JiPvQHo93pyAPZ3WlkGw8gS+VqmiDDXKt76tI=,tag:peToEZzD4K0WXtl2TsyeFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZk1oeFF1YUhBNFZod3RB
            bVdEYkVmTHhCRWhsUTFmL04zSFY1Um45L0NjCm9LUm1xeVZqKzh5UFREN0JwNTdV
            YlJzeC9EY2NtR01obmxnZTBkQ2J5ZEkKLS0tIDBPRTBSM2lVMFV2NVFIUERDUWdV
            M0U4V2gzWU1aZDNKYzZwakZHazBGOTQKnNjtH2+a+0da0szJjK04qOh3WH6UO7sF
            By5Cw/PUCTLqHSqUo8kV6tN/xURWG6eeKdiwGGf9JK6F5VYTdnpQ3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-18T20:39:53Z"
    mac: ENC[AES256_GCM,data:O7mWaq81jlKtphAs7NSBDfC/WRItkyxWLF0mQSZnLrQ2v/Av0RO9ZnXSRVOBWSaHpz8AGCnQugFwn+g/3S6JysFqe6Wc/mT7TJ/aHluy+v5/H9+sBn/xMMgRCUY/kR4pZhnW5YBW8jWOz5k2H7qrUskDPC2fkVJfaRPGIhb3M1k=,iv:gLHWSLkcWuaGrWHTotf2x08yw39DruzR68WLlY8s14k=,tag:4HHxHkx7qXd+X0o02TNhuQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
