#ENC[AES256_GCM,data:x0MzokxnkuCN1zUvbYgw/rfcrFG2GiLzNyvzdmwXfdCe8J2+8rYyoSzcKfzhwKYUyjAtchtO/Q8ZHA==,iv:areLdJCPHdR/nxNLIkgw0KnqZKmb+r1ltmj3DWFwt68=,tag:7pNJMfF1xU35Ya4y/BlM/A==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: tbz-treeregister-secret
type: Opaque
data:
    GE_CLIENT_SECRET: ENC[AES256_GCM,data:j+4drvCLEMQHc4/yOPtLp0va0gYWlqmXO7HsEnWnYjTuormUzgcbCCtCgk0=,iv:VmY+XO8ooIuMT7DnjM7EbgKv+FmgwgeD7MDDNyRGKM4=,tag:KlG5Up/7yKKiE6Ry15nyGA==,type:str]
    GE_DB_URL: ENC[AES256_GCM,data:Y/YQNZEkjKCmCOHcxV+cjj9FOstORu06AeeClvgaieQACLgBG5NynHLtA/QdTYjssOR0Bv8hLzapLkai/WmypixNSFyLL8upLIZIXCEbWydS4100efOPvMrtzlyYYmhJxmE2xoCP70uJLbneW34GF1YmW8wjytoUk+p4yQ==,iv:4clyJ+JiPvQHo93pyAPZ3WlkGw8gS+VqmiDDXKt76tI=,tag:peToEZzD4K0WXtl2TsyeFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZk1oeFF1YUhBNFZod3RB
            bVdEYkVmTHhCRWhsUTFmL04zSFY1Um45L0NjCm9LUm1xeVZqKzh5UFREN0JwNTdV
            YlJzeC9EY2NtR01obmxnZTBkQ2J5ZEkKLS0tIDBPRTBSM2lVMFV2NVFIUERDUWdV
            M0U4V2gzWU1aZDNKYzZwakZHazBGOTQKnNjtH2+a+0da0szJjK04qOh3WH6UO7sF
            By5Cw/PUCTLqHSqUo8kV6tN/xURWG6eeKdiwGGf9JK6F5VYTdnpQ3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-30T17:37:44Z"
    mac: ENC[AES256_GCM,data:IvaULQ2NWp0LPgNVqdbdl5CthoxsvpZONQwJIjUYcdVhPVk5WkfBy+ccIKec+ffm5geM13vEZgdKqIZAPF7ueuGPdTQTDsMq8AYPniXGVy2GeBN64pm1lZ3E9MC9NOwz6r67i+/lAW3d1BfFGbUIPmb2b84Ed2C2OnyxqVIVQXk=,iv:Tyzao2tfm+Rj1cSYYJ5LXaCQioycynkS5vzf8ceZb0o=,tag:7QYtH9mXEdKG4oNeuaKHDA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.4
