# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: tbz-treeregister
spec:
  selector:
    app: tbz-treeregister
  type: ClusterIP
  ports:
  - name: tbz-treeregister 
    protocol: TCP
    port: 80
    targetPort: 6123

